### PR TITLE
Make logos smaller on mobile

### PR DESCRIPTION
**Pull request by yassinya**

### CODE REVIEW

**Comment by ezl** [comment]
question: it seems you're setting the width of each image separately using w-32, w-28 etc...

(A) is this because you're manually setting each image size in the browser differently, then letting the browser width determine if it should cascade to the next row?
(B) if so why is this preferable to setting, for example: wide viewport = 4 columns, mobile viewport = 2 columns?

@yassinya

**Comment by yassinya** [comment]
@ezl  I am setting each image’s width independently because they have different dimensions. So I’m just trying to make them as close as possible to each other visually in terms of dimension.

In order to display them vertically and horizontally (depending the screen size), I am setting their container to `flex-row` in large screens, and `flex-col `on mobile

**Comment by ezl** [comment]
@yassinya per our discussion on screenshare, please make it be 2 rows of 2 images on mobile and tablet, then 1 row of 4 on desktop.

**Review by ezl — APPROVED** [review]
looks great! approving.

**Pull request merged**
